### ISSUE TITLE
Server won't run even if i had the correct yungsapi.

### ISSUE THREAD

**Issue by Endirious** [YUNG-GANG/YUNGs-Bridges#16]
Details:
	Mod File: YungsBridges-Forge-1.16.4-1.0.1.jar
	Failure message: Mod yungsbridges requires yungsapi 1.16.4-Forge-12 or above
		Currently, yungsapi is not installed
	Mod Version: 1.16.4-1.0.1
	Mod Issue URL: https://github.com/yungnickyoung/YUNGs-Bridges/issues
	Exception message: MISSING EXCEPTION MESSAGE
Stacktrace:
	at net.minecraftforge.fml.CrashReportExtender.lambda$dumpModLoadingCrashReport$7(CrashReportExtender.java:74) ~[forge:?] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1259) ~[?:1.8.0_275] {}
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:72) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:37) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_275] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_275] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:37) ~[custom.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:49) [custom.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:46) [custom.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:43) [custom.jar:?] {}

**Comment by Endirious** [comment]
Full file
[crash-2022-05-24_17.54.49-fml.txt](https://github.com/YUNG-GANG/YUNGs-Bridges/files/8765307/crash-2022-05-24_17.54.49-fml.txt)

**Comment by williambl** [comment]
YUNG's API is not listed in your logs. Also, some other mods you have installed are missing dependencies.
