### ISSUE TITLE
Cannot invoke "com.alibaba.fastjson.JSONArray.size()" because "modary" is null

### ISSUE THREAD

**Issue by Kino0208** [YUNG-GANG/YUNGs-Bridges#17]
java.net.MalformedURLException: no protocol: 

         at java.base/java.net.URL.<init>(URL.java:674)
         at java.base/java.net.URL.<init>(URL.java:569)
         at java.base/java.net.URL.<init>(URL.java:516)
         at z2bguoguo.jiemian.geturl(jiemian.java:53)
         at z2bguoguo.zhixing.run(zhixing.java:60)
 
 java.lang.NullPointerException: Cannot invoke "com.alibaba.fastjson.JSONArray.size()" because "modary" is null
         at z2bguoguo.jiemian.getmodfilenames(jiemian.java:91)
         at z2bguoguo.zhixing.run(zhixing.java:61)
 
[latest.log](https://github.com/YUNG-GANG/YUNGs-Bridges/files/8963892/latest.log)

**Comment by williambl** [comment]
This doesn't seem to have anything to do with YUNG's Bridges. Your error seems to be related to this mod: https://github.com/z2bguoguo/zdgxmc/tree/master
